version: "3.9"
services:
  api:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./src
        target: /usr/src/app/src
  postgresdb:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: code-challenge
      POSTGRES_PASSWORD: code-challenge